# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseNode@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      mkdir deploy
      cp -R .next deploy/.next
      cp -R public deploy/public
      cp -R node_modules deploy/node_modules
      cp package.json deploy/
      cp next.config.js deploy/ || true
      cd deploy
      zip -r ../frontend.zip .
    displayName: 'Prepare deployment zip'

  - upload: $(Build.ArtifactStagingDirectory)/frontend.zip
    artifact: drop
    timeoutInMinutes: 15

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'sportlazeV2frontend'
      appType: 'webApp'
      WebAppName: 'sportlazeV2frontend'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/frontend.zip'
      DeploymentMethod: 'runFromPackage'