trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseNode@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
      cp -R .next/static .next/standalone/.next/static
    displayName: 'Install dependencies, build in standalone mode, and copy static assets'

  - script: |
      cd .next/standalone
      zip -r $(Build.ArtifactStagingDirectory)/frontend.zip .
    displayName: 'Archive standalone build for deployment'

  - upload: $(Build.ArtifactStagingDirectory)/frontend.zip
    artifact: drop
    timeoutInMinutes: 15

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'sportlazeV2frontend'
      appType: 'webApp'
      WebAppName: 'sportlazeV2frontend'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/frontend.zip'
      DeploymentMethod: 'runFromPackage'
