trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  NEXT_PUBLIC_API_BASE_URL: 'https://lazeapi-v2.onrender.com/api'
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: '292887638276-kk8gmqfsjivcnjujhsiqiu5d62rkocqt.apps.googleusercontent.com'  
  NEXT_PUBLIC_GOOGLE_REDIRECT_URL: 'https://sportlazev2frontend-h4bzchbpb2drcpa8.eastus2-01.azurewebsites.net/'

steps:
  - task: UseNode@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      echo "NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL" >> .env.production
      echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID" >> .env.production
      echo "NEXT_PUBLIC_GOOGLE_REDIRECT_URL=$NEXT_PUBLIC_GOOGLE_REDIRECT_URL" >> .env.production
      npm install
      npm run build
      cp -R .next/static .next/standalone/.next/static
    displayName: 'Install dependencies, build in standalone mode, and copy static assets'
    env:
      NEXT_PUBLIC_API_BASE_URL: $(NEXT_PUBLIC_API_BASE_URL)
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: $(NEXT_PUBLIC_GOOGLE_CLIENT_ID)
      NEXT_PUBLIC_GOOGLE_REDIRECT_URL: $(NEXT_PUBLIC_GOOGLE_REDIRECT_URL)

  - script: |
      cd .next/standalone
      zip -r $(Build.ArtifactStagingDirectory)/frontend.zip .
    displayName: 'Archive standalone build for deployment'

  - upload: $(Build.ArtifactStagingDirectory)/frontend.zip
    artifact: drop
    timeoutInMinutes: 15

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'sportlazeV2frontend'
      appType: 'webApp'
      WebAppName: 'sportlazeV2frontend'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/frontend.zip'
      DeploymentMethod: 'runFromPackage'
